[package]
name = "example"
authors = ["crjeder <crjeder@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"
version = "0.2.1"

[dependencies]
embedded-hal = "0.2.4"
bitmatch = "0.1.1"
nb = "1.0.0"
rppal = { version = "0.12.0", features = ["hal"] }
hx711_spi = { path = "../" }
