[package]
name = "example"
authors = ["crjeder <crjeder@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
nb = "1.0.0"
rppal = { version = "0.12.0", features = ["hal"] }
hx711_spi = { path = "../" }
