[package]
name = "hx711_spi"
version = "0.1.0"
authors = ["crjeder <crjeder@gmail.com>"]
edition = "2018"

[dependencies]
rppal = { version = "0.11.3", features = ["hal"] }
embedded-hal = "0.2.4"
bitmatch = "0.1.1"
