[package]
name = "hx711_spi"
description = "A platform agnostic driver to interface with the HX711 using SPI"
categories = ["embedded", "hardware-support"]
keywords = ["embedded-hal-driver", "embedded-hal", "hx711", "amplifier", "driver"]
authors = ["crjeder <crjeder@gmail.com>"]
repository = "https://github.com/crjeder/hx711_spi"
readme = "README.md"
documentation = "https://docs.rs/hx711_spi"
license = "MIT OR Apache-2.0"
edition = "2021"
version = "0.8.0"
include = ["src/lib.rs", "LICENSE", "README.md", "CHANGELOG.md"]

[dependencies]
embedded-hal = "1.0"
embedded-hal-async = "1.0"
bitmatch = "0.1.1"
maybe-async = { version = "0.2.10"}
# features = ["is_sync"] 

[features]
invert-sdo = []
is_sync = []

[dev-dependencies]
test-case = "3.3"
# for the Raspberry Pi example
rppal = { version = "0.18", features = ["hal"] }
