name: Rust

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy
    
    - name: Lint
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings   
          
    - name: Build
      run: | 
        cargo check
        cargo build --verbose
    
    - name: Run tests
      run: cargo test --verbose

  ensure_no_std:
    name: Ensure no_std
    runs-on: ubuntu-latest
    steps:
      - name: Download cargo-nono
        run: cargo install cargo-nono
      - name: Run check
        run: cargo nono check
