name: Rust

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Update
      run: |
          rustup update
          rustup component add clippy
    
    - name: Lint
      run: |
          cargo clippy -- -D warnings   
#          cargo fmt -- --check
          
    - name: Build
      run: | 
        cargo check
        cargo build 
    
    - name: Run tests
      run: cargo test 

#  ensure_no_std:
#    name: Ensure no_std
#    runs-on: ubuntu-latest
#    steps:
#      - name: Download cargo-nono
#        run: RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-nono
#        run: curl -LSfs https://japaric.github.io/trust/install.sh | sh -s -- --git hobofan/cargo-nono
#      - name: Run check
#        run: cargo nono check
