name: Rust

on:
  push:
    paths: 
      - '**/Cargo.toml'
      - '**/.github/workflows/*'
      - '**/src/*'
  pull_request:
    paths:
      - '**/Cargo.toml'
      - '**/.github/workflows/*'
      - '**/src/*'

env:
  CARGO_TERM_COLOR: always
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Cache cargo packages
      id: cargo-cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/
          ~/target/
          ~/Cargo.lock
        key: rust
        restore-keys: rust-${{ github.run_id }}

    - name: Update
      run: |
        rustup default nightly
        rustup update
        rustup default nightly   

    - name: binstall form binary
      id: from_binary
      continue-on-error: true
      run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
    
    - name: binstall from source
      if: ${{ steps.from_binary.outcome == 'failure' }}
      run:  cargo install cargo-binstall
    
    - name: create directory structure
      run: |
        mkdir ~/target/
        touch ~/Cargo.lock

    - name: check version 
      run: rustc --version

  build_and_test:
    needs: install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Cache cargo packages
      id: cargo-cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/
          ~/target/
          ~/Cargo.lock
        key: rust

    - name: Verify
      run: cargo verify-project
      
    - name: Build
      run: cargo build 
  
    - name: Run tests
      run: cargo test 
  
  secret_scan:
    needs: [install, build_and_test]
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v4
  
      - name: Cache cargo packages
        id: cargo-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/
            ~/target/
            ~/Cargo.lock
          key: rust
      
      - name: fencer
        run: |
          cargo binstall --no-confirm fencer
          fencer --project_dir ./
  
  check_for_bloat:
    needs: [install, build_and_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  
      - name: Cache cargo packages
        id: cargo-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/
            ~/target/
            ~/Cargo.lock
          key: rust
         
      - name: cargo diet
        run: |
          cargo binstall --no-confirm cargo-diet
          cargo diet --dry-run
  
  audit_for_vulnerabilities:
    needs: [install, build_and_test]
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v4
  
      - name: Cache cargo packages
        id: cargo-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/
            ~/target/
            ~/Cargo.lock
          key: rust
      
      - name: check_binaries
        continue-on-error: true
        run: |
          cargo --list
          ls ~/.cargo/bin/cargo-binstall
          
      - name: audit
        run: |
          cargo binstall --no-confirm cargo-audit
          cargo audit
  
  check_licenses:
    needs: [install, build_and_test]
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v4
  
      - name: Cache cargo packages
        id: cargo-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/
            ~/target/
            ~/Cargo.lock
          key: rust
      
      - name: cargo deny
        run: |
          cargo binstall --no-confirm cargo-deny
          cargo deny check
  
  Sonatype_OSSIndex: 
    needs: [install, build_and_test]
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v4
  
      - name: Cache cargo packages
        id: cargo-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/
            ~/target/
            ~/Cargo.lock
          key: rust
             
      - name: cargo pants
        env: 
          OSS_INDEX_API_KEY: ${{ secrets.OSS_INDEX_API_KEY }}
        run: |
           cargo binstall --no-confirm cargo-pants
           cargo pants -v
  
  Outdated_dependencies:
    needs: [install, build_and_test]
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v4
  
      - name: Cache cargo packages
        id: cargo-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/
            ~/target/
            ~/Cargo.lock
          key: rust
      
      - name: cargo_outdated
        run: |  
          cargo binstall --no-confirm cargo-outdated
          cargo outdated
  
  Unused_dependencies:
    needs: [install, build_and_test]
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v4
  
      - name: Cache cargo packages
        id: cargo-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/
            ~/target/
            ~/Cargo.lock
          key: rust
      
      - name: cargo udeps
        run: |
          cargo binstall --no-confirm cargo-udeps
          cargo udeps

  Comply_with_formating_standard:
    needs: [install, build_and_test]
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v4
  
      - name: Cache cargo packages
        id: cargo-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/
            ~/target/
            ~/Cargo.lock
          key: rust
      
      - name: rustfmt
        run: |
          rustup component add rustfmt
          cargo fmt --all --check
   
  Comply_with_versioning_standard:
    needs: [install, build_and_test]
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v4
  
      - name: Cache cargo packages
        id: cargo-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/
            ~/target/
            ~/Cargo.lock
          key: rust
          
      - name: Check Semver
        run: |
          cargo binstall --no-confirm cargo-semver-checks
          cargo semver-checks check-release -v

  Spellcheck:
    needs: [install, build_and_test]
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v4
  
      - name: Cache cargo packages
        id: cargo-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/
            ~/target/
            ~/Cargo.lock
          key: rust
      
      - name: cargo spellcheck
        run: | 
          cargo binstall cargo-spellcheck
          cargo spellcheck check

  no-std-check:
    needs: [install, build_and_test]
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v4
  
      - name: Cache cargo packages
        id: cargo-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/
            ~/target/
            ~/Cargo.lock
          key: rust
      
      - name: check if library is no-std compatible
        run: | 
          cargo binstall cargo-no-std-check
          cargo no-std-check

# ideas for future improvement
# don't forget to run ```cargo owner --add rust-bus-owner``` on first publication
#
# [x] cargo no-std-check
# [x] speed things up using cargo-binstall
# [x] cargo audit (is it integrated somewhere?)
# [ ] cargo bloat (not suitable for automation)
# [x] cargo semver-checks
# [x] cargo spellcheck
# [ ] cargo unused-features (not suitable for automation)
# [ ] mcarton/rust-herbie-lint (warnings for unstable floating point expressions)(not suitable for automating)
# [ ] Prusti (verifies absence of e. g. panic!())
# [ ] Rudra (memory safety check)
# [x] rustfmt
# [ ] cargo-action-fmt (Converts cargo check (and clippy) JSON output to the GitHub Action error format)
# [ ] cargo tarpaulin (code coverage reporting tool)
# [ ] cargo crev
# [ ] cargo geiger (does not run)
# [ ] Husky
# [ ] cargo-about (not suitable for automation)
# [ ] cargo-msrv (not suitable for automation)
# [x] cargo-udeps 
# [x] cargo-diet
# [x] cargo verify-project
#- if: steps.cargo-cache.outputs.cache-hit != 'true'