name: Rust

on:
  push:
    paths: 
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '**/.github/workflows/*'
      - '**/src/*'
  pull_request:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '**/.github/workflows/*'
      - '**/src/*'

env:
  CARGO_TERM_COLOR: always
  GH_TOKEN: ${{ secrets.gh_token }}

jobs:
  cargo_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Update
      run: |
        rustup default nightly
        rustup update     
    
    - name: rustfmt
      run: |
        rustup component add rustfmt
        cargo fmt --all -- --check

    - name: Build
      run: cargo build 
    
    - name: Run tests
      run: cargo test 

    - name: Create documentation
      run: cargo doc 
      
    - name: binstall
      run: |
        cargo install cargo-binstall
# curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

    - name: Check Semver
      run: |
        cargo binstall --no-confirm cargo-semver-checks
        cargo semver-checks

    - name: audit
      run: |
        cargo binstall --no-confirm cargo-audit
        cargo audit

    - name: cargo deny
      run: |
        cargo binstall --no-confirm cargo-deny
        cargo deny check

    - name: cargo_outdated
      run: |  
        cargo binstall --no-confirm cargo-outdated
        cargo outdated

    - name: cargo udeps
      run: |
        cargo binstall --no-confirm cargo-udeps

# nono does not compile anymore    
#    - name: ensure_no_std
#      run: |
#        RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-nono
#        cargo nono check
        
    - name: cargo pants
      env:
        OSS_INDEX_API_KEY: ${{ secrets.OSS_INDEX_API_KEY }}
      run: |
       cargo binstall --no-confirm cargo-pants
       cargo pants

  
# Works with nightly only
#  cargo-udeps:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v2
#
#      - name: Install nightly toolchain
#        uses: actions-rs/toolchain@v1
#        with:
#          toolchain: nightly
#          override: true
#
#      - name: Run cargo-udeps
#        uses: aig787/cargo-udeps-action@v1
#        with:
#          version: 'latest'
#          args: '--all-targets'      

# ideas for future improvement
# don't forget to run ```cargo owner --add rust-bus-owner``` on first publication
#
# [x] speed things up using cargo-binstall
# [x] cargo audit (is it integrated somewhere?)
# [ ] cargo bloat (not suitable for automation)
# [x] cargo semver-checks
# [ ] cargo spellcheck (not suitable for automation)
# [ ] cargo unused-features (not suitable for automation)
# [ ] mcarton/rust-herbie-lint (warnings for unstable floating point expressions)(not suitable for automating)
# [ ] Prusti (verifies absence of e. g. panic!())
# [ ] Rudra (memory safety check)
# [x] rustfmt
# [ ] cargo-action-fmt (Converts cargo check (and clippy) JSON output to the GitHub Action error format)
# [ ] cargo tarpaulin (code coverage reporting tool)
# [ ] cargo crev
# [ ] cargo geiger (does not run)
# [ ] Husky
# [ ] cargo-about (not suitable for automation)
# [ ] cargo-msrv (not suitable for automation)
# [ ] cargo-diet (not suitable for automation)
# [ ] cargo-udeps (requires nightly)

## Tasks to do bevore publish
#  cargo command | comment |
# |---|---|
# | cargo owner --add rust-bus-owner | only once |
# | cargo geiger | allways has warnings which have to be manually vetetd |
# | cargo crev | manually done at release |
# | cargo release | finis up! |
# | cargo command | comment |
# |---|---|
# | cargo-strip | strip binary |
# | cargo diet | done bevore final build |
# | release-plz release | automates the release process |
# 
## Subcommands to Test
#
# | cargo command | comment |
# |---|---|
# | cargo tree | nice tree of dependencies |
# | vargo vet | testing it, it's under development |
# | cargo udeps | works only with nightly compiler |
# | cargo mutants | check test coverage |
# | cargo checkmate | test and see if it can streamline tasks |
#
## Not Needed
#
# | cargo command | comment |
# | --- | --- |
# | cargo bloat|  replaced by cargo diet
# | cargo duplicates | is handled by cargo deny |
